### ISSUE TITLE
CSRF is in the wrong directory resulting in the templates not loading

### ISSUE THREAD

**Issue by vortexau** [bugcrowd/templates#497]
https://github.com/bugcrowd/templates/tree/master/submissions/description/cross_site_scripting_xss/cross_site_request_forgery_csrf

CSRF is a top level category, not a sub category of XSS, and it needs to be moved to the parent directory as per VRT.

**Comment by vortexau** [comment]
@RRudder - can you please review and PR a fix?

**Comment by RRudder** [comment]
Closing this issue as it has been resolved in the above PR, approved, and merged into the main branch
